<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbynumletter($numLetter)
    {
        $questionsRepository = $this->getRepository('AppBundle:Question');
        $queryBuilder = $questionsRepository->createQueryBuilder('q');
        $queryBuilder
            ->andWhere('CHAR_LENGTH(q.text) = :numletter')
            ->setParameter('numletter', $numLetter)
        ;
        $query = $queryBuilder->getQuery();
        return $query->getResult();

    }
}
