<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBynumletter($numLetter)
    {
        //$questionsRepository = $this->get('AppBundle:Question');
        $qb = $this->createQueryBuilder('q');
        $qb
            ->select('q')
            ->andWhere('CHAR_LENGTH(q.text) = :numletter')
            ->setParameter('numletter', $numLetter)
        ;
        $query = $qb->getQuery();
        return $query->getResult();

    }

    public function findBynumwords($numWords)
    {
        //$questionsRepository = $this->get('AppBundle:Question');
        $qb = $this->createQueryBuilder('q');
        $qb
            ->select('q')
            //->andWhere('(LENGTH(text) - LENGTH(replace(text, " ", "")))+1 = :numwords')
            ->andWhere('WORD_COUNT(q.text) = :numwords')
          ->setParameter('numwords', $numWords)
        ;
        $query = $qb->getQuery();
        return $query->getResult();

    }

}
